---
title: "BX ARIMA models with TimeTk"
author: "Daniel L."
date: "3/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, results='hide'}
library(tidyverse)
library(tidymodels)
library(lubridate)
library(RSocrata)
library(tsfknn)
library(fpp3)
library(tsibble)
library(feasts)
library(timetk)
```


```{r}
load("C:\\Users\\Daniel\\Desktop\\R\\STAT_790\\STAT_790_Case_Seminar\\data_prep.Rdata")
load("meeting_6.RData")
```

```{r}
bx_ts2 %>% glimpse()
```
```{r plotly of bxts_2}
bx_ts %>% plot_time_series((month), total_waste)
```

## bx_ts can't be a tsibble. It must be a tibble or data.frame. From the timetk::tk_tsfeatures documentation

```{r walmart example}
walmart_sales_weekly %>%
    group_by(id) %>%
    tk_tsfeatures(
      .date_var = Date,
      .value    = Weekly_Sales,
      .period   = 52,
      .features = c("frequency", "stl_features", "entropy", "acf_features", "mean"),
      .scale    = TRUE,
      .prefix   = "ts_"
    )
```

```{r}
head(DSNY_train)
```

Thought it was best to use the training data, and use the total_waste collected as our value

```{r DSNY_train}
DSNY_train %>%
    group_by(borough) %>%
    tk_tsfeatures(
      .date_var = month,
      .value    = total_waste,
      .period   = 12,
      .features = c("frequency", "stl_features", "entropy", "acf_features", "mean"),
      .scale    = TRUE,
      .prefix   = "ts_"
    )
```

```{r diagnostics plot}
# DSNY_third_bronx %>% plot_acf_diagnostics(
#   .date_var = dplyr::month(month),
#   .value = total_waste
)
```


```{r}
knitr::purl("sixth_meetings_notes_timetk.Rmd")
```

