---
title: "Nineth meeting notes"
author: "Daniel L."
date: "4/9/2022"
output: html_document
---

```{r echo=FALSE, results='hide', error=FALSE, include=FALSE}
library(tidyverse)
library(lubridate)
library(RSocrata)
library(tsfknn)
library(fpp3)
library(tsibble)
library(feasts)
library(timetk)
library(modeltime)
library(zoo)
```

```{r}
load("C:/Users/Daniel/Desktop/R/STAT_790/STAT_790_Case_Seminar/BX_ts.RData")
load("C:\\Users\\Daniel\\Desktop\\R\\STAT_790\\STAT_790_Case_Seminar\\data_prep.Rdata")
```

```{r arima001 constant}
# and P=1, D=1
DSNY_BX_zoo_ts <- ts(DSNY_third_bronx[,-1], 
                     start = as.yearmon(DSNY_third_bronx$month)[1], 
                     frequency = 12)

bx_arima001_cons_110_12 <- bx_ts %>% 
  model(bx_arima001_cons_110_12 = ARIMA(total_waste ~ 1 + 
                                          pdq(0,0,1) + 
                                          PDQ(1,0,0, period = 12)))

zoo_arima001_cons_110_12fit <- arima(DSNY_BX_zoo_ts, 
                                order = 1 + c(0,0,1),
                                seasonal = list(order = c(1,1,0L), 
                                                period = 12))

res_arima001_cons_110_12 <- zoo_arima001_cons_110_12fit$residuals
acf(res_arima001_cons_110_12, lag.max = 36)
pacf(res_arima001_cons_110_12, lag.max = 36)
accuracy(bx_arima001_cons_110_12)
glance(bx_arima001_cons_110_12)

```


```{r}
bx_total_waste_fit_final <-  bx_ts %>% model(stepwise = ARIMA(total_waste),
                                       search = ARIMA(total_waste, stepwise = FALSE),
                                       arima000 = ARIMA(total_waste ~ 1 + 
                                                                            pdq(0,0,0) + 
                                                                            PDQ(1,0,0, period = 12)),
                                      arima011 = ARIMA(total_waste ~ 1 + 
                                                                         pdq(0,1,1) + 
                                                                         PDQ(1,0,0, period = 12)))
#arima000_constant_seasonal
#bx_arima011_cons_100_12
# bx_total_waste_fit %>% 
#   forecast(h = 8) %>% 
#   autoplot(bx_ts) + labs(x = "Month Number",
#                          y = "Total Waste")

bx_total_waste_fit_final %>% 
  forecast(h = 8) %>% 
  autoplot(bx_ts2,
           level = NULL) +
  labs(x = "Month Number",
       y = "Tonnage",
       title = "Bronx Total Waste Tonnage",
       subtitle = "(Jan 2015 - Dec 2020)") +
  guides(colour = guide_legend(title = "Forecast"))

accuracy(bx_total_waste_fit_final)

bx_total_waste_fit_final %>% select(.model = arima000) %>% report()
bx_total_waste_fit_final %>% select(.model = arima011) %>% report()
 
bx_total_waste_fit_final %>% 
  forecast(h = 8)

bx_total_waste_fit_final %>% pivot_longer(everything(), 
                                          names_to = "Model name",
                                          values_to = "Orders")

glance(bx_total_waste_fit_final) %>% arrange(AICc) %>% select(.model:BIC)

bx_total_waste_fit_final %>% select(arima000) %>% gg_tsresiduals(lag=36)

augment(bx_total_waste_fit_final) %>% 
  filter(.model == "arima000") %>% 
  features(.innov, 
           ljung_box,
           lag = 36,
           dof=2)
#The model fails the Ljung Box test, p-value = 0.0007
augment(bx_total_waste_fit_final) %>% 
  filter(.model == "arima011") %>% 
  features(.innov, 
           ljung_box,
           lag = 36,
           dof=2)
#The model fails the Ljung Box test, p-value = 0.047

forecast(bx_total_waste_fit_final, h = 6) %>% 
  filter(.model == ('arima011')) %>% 
  autoplot(bx_ts2,
           level = NULL) +
  labs(x = "Month Number",
       y = "Tonnage",
       title = "Bronx Total Waste Tonnage",
       subtitle = "(Jan 2015 - Dec 2020)") +
  guides(colour = guide_legend(title = "Forecast"))
```

When models are compared using AICc values, it is important that all models have the same orders of differencing. However, when comparing models using a test set, it does not matter how the forecasts were produced — the comparisons are always valid.

```{r DSNY_BX_train}
total <- list(
  total = ~ sum(.x, na.rm = TRUE)
)
# DSNY_train %>%
#   filter(borough_id==2,
#          communitydistrict==3) %>%
#   ggplot(aes(month,refusetonscollected)) + geom_line()

# DSNY_train %>%
#   filter(borough_id==2) %>%
#   select(-borough, borough_id) %>%
#   arrange(month)
  
# demo_2019_acs5yr_cdta %>%
#   group_by(Borough) %>% 
#   select(Borough,
#            ends_with("E",
#                      ignore.case = FALSE)) %>%
#   summarise(across(where(is.numeric), total, .names = "{.col}_{.fn}"))

# DSNY_train %>%
#   filter(borough_id==2) %>%  
#   group_by(month, communitydistrict, borough) %>% 
#   select(-borough, -borough_id, communitydistrict) %>%
#   arrange(month) %>%
#   summarise(across(where(is.numeric), total, .names = "{.col}_{.fn}"))

DSNY_Qns_train <- DSNY_train %>%
  group_by(month, borough) %>% 
  select(-borough, -borough_id, -communitydistrict) %>%
  arrange(month) %>%
  summarise(across(where(is.numeric), total, .names = "{.col}_{.fn}")) %>% 
  filter(borough == "Queens") %>% 
  ungroup()

DSNY_BX_train <- DSNY_train %>%
  group_by(month, borough) %>% 
  select(-borough, -borough_id, -communitydistrict) %>%
  arrange(month) %>%
  summarise(across(where(is.numeric), total, .names = "{.col}_{.fn}")) %>% 
  filter(borough == "Bronx") %>% 
  ungroup()

DSNY_train %>%
  filter(borough == "Bronx",
         communitydistrict==1) %>%
  group_by(month, borough, communitydistrict) %>% 
  select(-borough, -borough_id, -communitydistrict) %>%
  arrange(month) %>% 
  ungroup()
```
```{r as_tibble DSNY_BX_train}
# bx_ts2 %>% 
#   mutate(month_num = row_number()) %>% 
#   update_tsibble(index = month_num, regular = TRUE) %>% 
#   mutate(diff1 = difference(total_waste, differences = 1, order_by = Month))

# as_tsibble(DSNY_third_bronx_2, index = 'Month', regular = FALSE)

bx_ts_multi <- DSNY_BX_train %>% 
  mutate(month_num = row_number()) %>% 
  as_tsibble(., index = month_num, regular = TRUE)

qns_ts_multi <- DSNY_Qns_train %>% 
  mutate(month_num = row_number()) %>% 
  as_tsibble(., index = month_num, regular = TRUE)

# DSNY_BX_train %>% 
#   mutate(month_num = row_number()) %>% 
#   as_tsibble(., index = month, regular = FALSE)
```

```{r trying to get NYC total}
 # %>%
 #  summarise(across(where(is.numeric), total, .names = "{.col}_{.fn}"))

DSNY_train %>% 
  group_by(month, borough) %>% 
  select(-communitydistrict, borough_id) %>% 
  arrange(month) %>% 
  summarise(across(where(is.numeric), total, .names = "{col}_{.fn}"))

NYC_total <- DSNY_train %>% 
  group_by(month) %>% 
  select(-c(communitydistrict, borough_id)) %>% 
  arrange(month) %>% 
  summarise(across(where(is.numeric), total, .names = "{col}_{.fn}")) %>% 
  ungroup()

nyc_ts_multi <- NYC_total %>% 
  mutate(month_num = row_number()) %>% 
  as_tsibble(., index = month_num, regular = TRUE)

nyc_ts_multi2 <- NYC_total %>% 
  mutate(month_num = row_number()) %>% 
  as_tsibble(., index = month, regular = FALSE)
```

```{r NYC plots}
nyc_ts_multi %>% ggplot() + geom_point(mapping = aes(x = month, y = refusetonscollected_total))

nyc_ts_multi2 %>% autoplot(refusetonscollected_total)

nyc_ts_multi2 %>% 
  gg_season(refusetonscollected_total, labels = "right") +
  labs(x = "Month",
       y = "Refuse Collected (Tons)",
       title = "Seasonal plot: New York City Total Refuse Tons Collected")
nyc_ts_multi2 %>% gg_season(papertonscollected_total, labels = "right") +
  labs(x = "Month",
       y = "Paper Collected (Tons)",
       title = "Seasonal plot: New York City Total Paper Tons Collected")
nyc_ts_multi2 %>% gg_season(mgptonscollected_total, labels = "right") +
  labs(x = "Month",
       y = "MGP Collected (Tons)",
       title = "Seasonal plot: New York City Total Metal, Glass and Plastic Tons Collected")

nyc_ts_multi2 %>% gg_season(papertonscollected_total, period = "year")

nyc_ts_multi2 %>% gg_subseries(refusetonscollected_total, period = "year")
```

```{r}
# us_change %>%
#   select(-Consumption, -Income) %>%
#   pivot_longer(-Quarter) %>%
#   ggplot(aes(Quarter, value, colour = name)) +
#   geom_line() +
#   facet_grid(name ~ ., scales = "free_y") +
#   guides(colour = "none") +
#   labs(y="% change")

# bx_ts_multi %>%
#   select(-xmastreetons_total, -resorganicstons_total, -leavesorganictons_total, -schoolorganictons_total) %>%
#   ggplot(aes(month, value, colour = name)) +
#   geom_line() +
#   facet_grid(name ~ ., scales = "free_y") +
#   guides(colour = "none") +
#   labs(y="% change")
```

```{r attempt at a fit}
bx_tslm_fit <- bx_ts_multi %>% 
  model(tslm = TSLM(refusetonscollected_total ~ papertonscollected_total + mgptonscollected_total))

report(bx_tslm_fit)
```

intercept is 22279.9385, 