---
title: "Weather Attempts"
author: "Daniel L."
date: "4/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

[Weather data package](https://www.rdocumentation.org/packages/weatherData/versions/0.5.0)
```{r}
# install.packages("devtools")
# library("devtools")9
# install_github("Ram-N/weatherData")
library(weatherData)
```

```{r}
# getWeatherForDate(station_id = "KJFK", start_date = "2020-01-01")
```

[rwunderground](https://cran.r-project.org/web/packages/rwunderground/README.html)

```{r}
# devtools::install_github("ALShum/rwunderground")
rwunderground::set_api_key("0k71IwSc")
library(rwunderground)
library(tidyverse)
```

```{r}
my_weather_station <- "KNYNEWYO1620"
#set_location(PWS_id ="KNYNEWYO1653")
```
```{r}
# almanac(set_location(PWS_id ="KNYNEWYO1653"))
#history(set_location(zip_code = "11369"), date = "20050101")
```
```{r}
weather_data<-history(set_location(PWS_id = my_weather_station), date = "20170801")
```

# RNOAA

[rnoaa](https://docs.ropensci.org/rnoaa/)
[cran](https://cran.r-project.org/web/packages/rnoaa/rnoaa.pdf)

```{r}
#install.packages("rnoaa")
library('plyr')
library('rnoaa')
library(dplyr)
#https://www.ncdc.noaa.gov/cdo-web/webservices/v2
options(noaakey = "MopopkuFWTfdYEzIOlffzMnkBUdDqrgB")
```

```{r} 
ghcnd(stationid = "US1NYNY0074")
ncdc_stations(ghcnd(stationid = "US1NYNY0074"))
ncdc_datasets()
```

```{r}
ncdc_datasets(datasetid = 'NORMAL_MLY', stationid = "US1NYNY0074", startdate = 2022-01-01, enddate = 2022-03-01)
```

# App.tommorow.io
[Creating a Weather Data App Using Tomorrow.io API R Package](https://www.tomorrow.io/blog/creating-a-weather-data-app-using-tomorrow-io-api-r-package/)

```{r}
install.packages("githubinstall")
install.packages("httr")
#install.packages("Rtomorrow.io")
```

# OpenWeatherMap

https://crazycapivara.github.io/owmr/

https://openweathermap.org/api/

```{r}
#install.packages("owmr")
```

```{r}
library(owmr)

Sys.setenv(OWM_API_KEY = "acbab066c09fa497eb276f8a1216cb81")
```

```{r}
# get current weather data by city name
get_current("London", units = "metric") %>%
  owmr_as_tibble() %>% 
  names()
```

