---
title: "Playing with TidyCensus API"
author: "DL"
date: "2/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### CensusMetaData

```{r}
listCensusMetadata(name = "acs/acs1",
                   type = "variables")
```


## Getting started with censusapi
```{r}
library(censusapi)
library(tidycensus)
library(viridis)
```

```{r API key, warning=FALSE}
Sys.setenv(CENSUS_KEY = "741791920011136da47e8b205ca50942f4eb1ee0")
readRenviron("~/.Renviron")
Sys.getenv("CENSUS_KEY")
```

```{r}
apis <- listCensusApis()
View(apis)
```

```{r}
acs19 <- load_variables(year = 2019, dataset = 'acs5', cache = TRUE)
view(acs19)
```

```{r}
medval_md <- get_acs(geography = 'county', variables = 'B25077_001', state = 'MD', survey = 'acs5')
View(medval_md)
```

```{r}
medval_pgmd <- get_acs(geography = 'tract', variables = 'B25077_001', state = 'MD', county = 033, survey = 'acs5')
View(medval_pgmd)
```

```{r}
# no return values
#get_acs(year = 2019, geography = 'zcta', state = 'NY', zcta = '11369', variables = 'B08006_001', survey = 'acs1')

```

```{r}
get_acs(year = 2019, geography = 'zcta', state = 'NY', zcta = '11369', variables = 'B08006_001')
```


```{r}
listCensusMetadata(
    name = "timeseries/healthins/sahie", 
    type = "variables")
```

```{r}
getCensus(name = "acs/acs5", vintage = 2017,
vars = c("B01001_001E", "NAME", "B01002_001E", "B19013_001E"),
region = "tract:*", regionin = "state:06")
```

```{r}
getCensus(name = "acs/acs5",
vintage = 2017,
vars = c("NAME", "group(B19013)"),
region = "county:*")
```


```{r}
listCensusMetadata(
    name = "timeseries/idb/1year", 
    type = "variables")
```

```{r}
getCensus(name = "timeseries/idb/1year",
    vars = c("FIPS", "NAME", "AGE", "POP"),
    time = 2050) 
```

```{r}
getCensus(
    name = "timeseries/idb/1year",
    vars = c("NAME", "POP"),
    time = 2050,
    FIPS = "PO",
    AGE = "13:19")
```


```{r}
getCensus(
    name = "acs/acs5",
    vintage = 2017, 
    vars = c("NAME", "B19013_001E", "B19013_001EA", "B19013_001M", "B19013_001MA"), 
    region = "tract:Queens County")
    #regionin = "state:36")
```

```{r}
listCensusMetadata(
    name = "acs/acs5",
    vintage = 2019,
    type = "variables",
    group = "B19013")
```

