---
title: "Weather Attempts"
author: "Daniel L."
date: "4/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

[Weather data package](https://www.rdocumentation.org/packages/weatherData/versions/0.5.0)
```{r}
# install.packages("devtools")
# library("devtools")9
# install_github("Ram-N/weatherData")
library(weatherData)
```

```{r}
# getWeatherForDate(station_id = "KJFK", start_date = "2020-01-01")
```

[rwunderground](https://cran.r-project.org/web/packages/rwunderground/README.html)

```{r}
# devtools::install_github("ALShum/rwunderground")
rwunderground::set_api_key("0k71IwSc")
library(rwunderground)
```

```{r}
my_weather_station <- "KNYNEWYO1620"
#set_location(PWS_id ="KNYNEWYO1653")
```
```{r}
# almanac(set_location(PWS_id ="KNYNEWYO1653"))
#history(set_location(zip_code = "11369"), date = "20050101")
```
```{r}
#weather_data<-history(set_location(PWS_id = my_weather_station), date = "20170801")
```

# RNOAA

[rnoaa](https://docs.ropensci.org/rnoaa/)
[cran](https://cran.r-project.org/web/packages/rnoaa/rnoaa.pdf)

```{r}
#install.packages("rnoaa")
library('plyr')
library('rnoaa')
library(dplyr)
#https://www.ncdc.noaa.gov/cdo-web/webservices/v2
options(noaakey = "MopopkuFWTfdYEzIOlffzMnkBUdDqrgB")
```

```{r} 
ghcnd(stationid = "US1NYNY0074")
ncdc_stations(ghcnd(stationid = "US1NYNY0074"))
ncdc_datasets()
```

```{r}
ncdc_datasets(datasetid = 'NORMAL_MLY', stationid = "US1NYNY0074", startdate = 2022-01-01, enddate = 2022-03-01)
```

# App.tommorow.io
[Creating a Weather Data App Using Tomorrow.io API R Package](https://www.tomorrow.io/blog/creating-a-weather-data-app-using-tomorrow-io-api-r-package/)

```{r}
install.packages("githubinstall")
install.packages("httr")
#install.packages("Rtomorrow.io")
```

# OpenWeatherMap

https://crazycapivara.github.io/owmr/

https://openweathermap.org/api/

```{r}
#install.packages("owmr")
```

```{r}
library(owmr)
```

```{r}
# get current weather data by city name
get_current("11369", units = "metric") %>%
  owmr_as_tibble() %>% 
  names()
```

```{r}
nyc <- search_city_list("New York City") %>% as.list()


get_current(nyc$id, 
            units = "metric") %>% 
  owmr_as_tibble() %>% .[,1:6]

res <- find_cities_by_geo_point(
  lat = nyc$lat,
  lon = nyc$lon,
  cnt = 5,
  units = "metric"
) %>% 
  owmr_as_tibble()

idx <- c(names(res[1:6]), "name")
res[,idx]

#get forecast
forecast <- get_forecast("New York City", 
                         units = "imperial") %>% 
  owmr_as_tibble()
forecast[,1:6]
```
NYC has id = 5128581, 

```{r}
#apply functs to some columns

funcs <- list(
  temp = round,
  wind_speed = round
)

forecast %<>% parse_columns(funcs)

#some templating
("{{dt_txt}}h {{temp}}°F, {{wind_speed}} m/s" %$$% forecast) %>% 
  head(10)
```

d# Weather.gov

(https://www.weather.gov/wrh/Climate?wfo=okx)

```{r}
library(tidyverse)
library(lubridate)
library(readxl)
precipitation_data <- read_excel("external_datasets/noaa_weather_data.xlsx", 
    sheet = "Monthly_Total_Precip")
avg_temperature <- read_excel("external_datasets/noaa_weather_data.xlsx", 
    sheet = "Monthly_Mean_Avg_Temperature")
avg_CDD <- read_excel("external_datasets/noaa_weather_data.xlsx", 
    sheet = "Monthly_Mean_CDD")
```

```{r}
# precipitation_data %>% as.Date(as.character(Year), format = "%Y")
# precipitation_data$ ymd(sprintf("%d-01-01", precipitation_data$Year))
```

```{r}
precipitation_data_2 <- precipitation_data %>% 
  pivot_longer(!Year, 
               names_to = "month",
               values_to = "avg_precip") %>% 
  filter(month != "Annual")

precipitation_data_2 <- precipitation_data_2 %>% 
  mutate("day" = rep(1, nrow(precipitation_data_2)))

# precipitation_data_2 %>% 
# mutate("day" = rep(1, nrow(precipitation_data_2))) success and failure

# precipitation_data_2 %>% 
#   filter(month != "Annual") %>% 
#   view() success

# with(precipitation_data_2, sprintf("%d-01-%02d", Year, month)) fail
# as.Date(with(precipitation_data_2, paste(Year, month, "01", sep ="-")), "%Y-%m-%d") fail

# precipitation_data_2 %>% 
#   mutate(date = make_date(Year, month, day)) fail

precipitation_data_2$date <- paste(precipitation_data_2$Year, precipitation_data_2$month, precipitation_data_2$day, sep="-") %>% ymd() %>% as.Date()

precipitation_data_2 <- precipitation_data_2 %>% 
  select(date, avg_precip)
```

```{r avg temp clean}
avg_temperature_2 <- avg_temperature %>% 
  pivot_longer(!Year, 
               names_to = "month",
               values_to = "avg_temp") %>% 
  filter(month != "Annual")

avg_temperature_2 <- avg_temperature_2 %>% 
  mutate("day" = rep(1, nrow(avg_temperature_2)))

avg_temperature_2$date <- paste(avg_temperature_2$Year, avg_temperature_2$month, avg_temperature_2$day, sep="-") %>% ymd() %>% as.Date()

avg_temperature_2 <- avg_temperature_2 %>% 
  select(date, avg_temp)
```

```{r avg CDD clean}
avg_CDD_2 <- avg_CDD %>% 
  pivot_longer(!Year, 
               names_to = "month",
               values_to = "avg_CDD") %>% 
  filter(month != "Annual")

avg_CDD_2 <- avg_CDD_2 %>% 
  mutate("day" = rep(1, nrow(avg_CDD_2)))

avg_CDD_2$date <- paste(avg_CDD_2$Year, avg_CDD_2$month, avg_CDD_2$day, sep="-") %>% ymd() %>% as.Date()

avg_CDD_2 <- avg_CDD_2 %>% 
  select(date, avg_CDD)
```

## Column binding

```{r one single dataframe}
bind_cols(precipitation_data_2, avg_temperature_2, avg_CDD_2)
#merge(precipitation_data_2, avg_temperature_2, avg_CDD_2, by = date, all.y = TRUE)
data12 <- inner_join(precipitation_data_2, avg_temperature_2, by = "date")
weather_data <- inner_join(data12, avg_CDD_2, by = "date")
save(weather_data, file = "weather_data.Rdata")
```

